-- Insert sample cars
INSERT INTO cars (host_id, title, description, price_per_day, brand, model, year, seats, transmission, fuel_type, location, images, features, requires_driver, state, rating) VALUES
-- Lagos Cars
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Tesla Model 3', 'Electric luxury sedan with autopilot', 85000, 'Tesla', 'Model 3', 2023, 5, 'automatic', 'electric', 'Lagos Island', ARRAY['/tesla-model-3.png'], ARRAY['Autopilot', 'Premium Sound', 'Leather Seats'], false, 'Lagos', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'BMW X5', 'Premium SUV perfect for families', 120000, 'BMW', 'X5', 2022, 7, 'automatic', 'petrol', 'Victoria Island', ARRAY['/bmw-x5-luxury-suv.png'], ARRAY['Panoramic Roof', 'Premium Sound', 'Leather Interior'], false, 'Lagos', 4.6),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Mercedes C-Class', 'Elegant sedan with premium features', 95000, 'Mercedes', 'C-Class', 2023, 5, 'automatic', 'petrol', 'Lekki', ARRAY['/mercedes-c-class-sedan.png'], ARRAY['Premium Interior', 'Advanced Safety', 'Luxury Comfort'], false, 'Lagos', 4.7),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Range Rover Evoque', 'Compact luxury SUV with style', 110000, 'Land Rover', 'Range Rover Evoque', 2023, 5, 'automatic', 'petrol', 'Ikoyi', ARRAY['/range-rover-evoque.png'], ARRAY['All-Wheel Drive', 'Panoramic Sunroof', 'Premium Audio'], false, 'Lagos', 4.5),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Toyota Camry', 'Reliable mid-size sedan for business', 65000, 'Toyota', 'Camry', 2022, 5, 'automatic', 'petrol', 'Surulere', ARRAY['/toyota-camry.png'], ARRAY['Backup Camera', 'Bluetooth', 'Fuel Efficient'], false, 'Lagos', 4.3),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Lexus ES 350', 'Luxury sedan with premium comfort', 105000, 'Lexus', 'ES 350', 2023, 5, 'automatic', 'petrol', 'Ajah', ARRAY['/lexus-es350.png'], ARRAY['Mark Levinson Audio', 'Heated Seats', 'Adaptive Cruise'], false, 'Lagos', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Honda Accord', 'Popular family sedan with efficiency', 55000, 'Honda', 'Accord', 2022, 5, 'automatic', 'petrol', 'Ikeja', ARRAY['/honda-accord.png'], ARRAY['Honda Sensing', 'Spacious Interior', 'Fuel Economy'], false, 'Lagos', 4.2),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Audi Q7', 'Premium 7-seater luxury SUV', 140000, 'Audi', 'Q7', 2023, 7, 'automatic', 'petrol', 'Victoria Island', ARRAY['/audi-q7.png'], ARRAY['Virtual Cockpit', 'Air Suspension', 'Bang & Olufsen Sound'], false, 'Lagos', 4.8),

-- Abuja Cars
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Mercedes E-Class', 'Executive sedan for business travel', 115000, 'Mercedes', 'E-Class', 2023, 5, 'automatic', 'petrol', 'Maitama', ARRAY['/mercedes-e-class.png'], ARRAY['MBUX Infotainment', 'Massage Seats', 'Ambient Lighting'], false, 'Abuja', 4.7),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'BMW 5 Series', 'Sport luxury sedan with performance', 125000, 'BMW', '5 Series', 2022, 5, 'automatic', 'petrol', 'Asokoro', ARRAY['/bmw-5-series.png'], ARRAY['Sport Package', 'Gesture Control', 'Harman Kardon Audio'], false, 'Abuja', 4.6),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Toyota Prado', 'Rugged SUV for all terrains', 95000, 'Toyota', 'Land Cruiser Prado', 2022, 7, 'automatic', 'petrol', 'Garki', ARRAY['/toyota-prado.png'], ARRAY['4WD', 'Hill Descent Control', 'Roof Rails'], true, 'Abuja', 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Infiniti QX80', 'Full-size luxury SUV', 130000, 'Infiniti', 'QX80', 2023, 8, 'automatic', 'petrol', 'Wuse 2', ARRAY['/infiniti-qx80.png'], ARRAY['Theater Seating', 'Around View Monitor', 'Bose Audio'], true, 'Abuja', 4.5),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Acura MDX', 'Premium 3-row family SUV', 100000, 'Acura', 'MDX', 2022, 7, 'automatic', 'petrol', 'Gwarinpa', ARRAY['/acura-mdx.png'], ARRAY['AcuraWatch', '3rd Row Seating', 'Premium Audio'], false, 'Abuja', 4.3),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Cadillac Escalade', 'Ultimate luxury full-size SUV', 180000, 'Cadillac', 'Escalade', 2023, 8, 'automatic', 'petrol', 'Central Business District', ARRAY['/cadillac-escalade.png'], ARRAY['Super Cruise', 'Premium Leather', 'AKG Studio Audio'], true, 'Abuja', 4.9),

-- Ekiti Cars
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Toyota Corolla', 'Economical and reliable sedan', 35000, 'Toyota', 'Corolla', 2021, 5, 'automatic', 'petrol', 'Ado-Ekiti', ARRAY['/toyota-corolla.png'], ARRAY['Toyota Safety Sense', 'Fuel Efficient', 'Spacious Cabin'], false, 'Ekiti', 4.1),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Nissan Altima', 'Comfortable mid-size sedan', 45000, 'Nissan', 'Altima', 2022, 5, 'automatic', 'petrol', 'Ikere-Ekiti', ARRAY['/nissan-altima.png'], ARRAY['ProPILOT Assist', 'Zero Gravity Seats', 'Bose Audio'], false, 'Ekiti', 4.2),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Hyundai Tucson', 'Compact SUV with modern features', 55000, 'Hyundai', 'Tucson', 2022, 5, 'automatic', 'petrol', 'Ado-Ekiti', ARRAY['/hyundai-tucson.png'], ARRAY['SmartSense Safety', 'Wireless Charging', 'Panoramic Sunroof'], false, 'Ekiti', 4.0),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Kia Sorento', 'Family-friendly 3-row SUV', 65000, 'Kia', 'Sorento', 2022, 7, 'automatic', 'petrol', 'Ijero-Ekiti', ARRAY['/kia-sorento.png'], ARRAY['UVO Connect', 'Captain Chairs', 'Harman Kardon Audio'], false, 'Ekiti', 4.3),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Mazda CX-5', 'Stylish compact crossover', 50000, 'Mazda', 'CX-5', 2022, 5, 'automatic', 'petrol', 'Ado-Ekiti', ARRAY['/mazda-cx5.png'], ARRAY['i-ACTIVSENSE', 'SKYACTIV Technology', 'Bose Audio'], false, 'Ekiti', 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Subaru Outback', 'Adventure-ready wagon SUV', 60000, 'Subaru', 'Outback', 2022, 5, 'automatic', 'petrol', 'Ikole-Ekiti', ARRAY['/subaru-outback.png'], ARRAY['Symmetrical AWD', 'EyeSight Safety', 'Roof Rails'], false, 'Ekiti', 4.2);

-- Insert sample services
INSERT INTO services (host_id, title, description, price, service_type, location, images, features, state, rating) VALUES
-- Lagos Services (Photography & Beauty as Hotel Services)
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Professional Wedding Photography Studio', 'Luxury wedding photography studio with drone shots and albums', 150000, 'hotel', 'Victoria Island', ARRAY['/wedding-photography-lagos.png'], ARRAY['Drone Shots', 'Photo Albums', 'Same Day Edit', 'Professional Equipment'], 'Lagos', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Bridal Hair & Makeup Suite', 'Professional bridal styling suite with premium products', 85000, 'hotel', 'Lekki', ARRAY['/bridal-makeup-lagos.png'], ARRAY['Bridal Makeup', 'Hair Styling', 'Premium Products', 'Trial Session'], 'Lagos', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'DJ & Sound Equipment Rental', 'Professional DJ equipment and sound system rental', 75000, 'souvenirs', 'Lagos Island', ARRAY['/dj-services-lagos.png'], ARRAY['Professional DJ Equipment', 'Sound System', 'Lighting Equipment', 'MC Equipment'], 'Lagos', 4.7),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Luxury Event Tent Decorations', 'Complete luxury event decorations and tent setup', 200000, 'tent_decorations', 'Ikoyi', ARRAY['/event-planning-lagos.png'], ARRAY['Luxury Tents', 'Floral Arrangements', 'Lighting Design', 'Complete Setup'], 'Lagos', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Premium Wedding Catering', 'Professional catering for weddings and events', 165000, 'catering', 'Ikeja', ARRAY['/catering-lagos.png'], ARRAY['Multiple Cuisines', 'Buffet Setup', 'Serving Staff', 'Equipment Included'], 'Lagos', 4.6),

-- Abuja Services 
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Corporate Photography Studio', 'Professional photography studio for business events', 120000, 'hotel', 'Central Business District', ARRAY['/corporate-photography-abuja.png'], ARRAY['Business Events', 'Professional Headshots', 'Corporate Branding', 'High Resolution'], 'Abuja', 4.7),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Executive Grooming Suite', 'Premium grooming and styling suite for professionals', 45000, 'hotel', 'Maitama', ARRAY['/executive-styling-abuja.png'], ARRAY['Professional Styling', 'Executive Grooming', 'Premium Products', 'Private Suite'], 'Abuja', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Live Band Equipment & Souvenirs', 'Professional band equipment rental and event memorabilia', 180000, 'souvenirs', 'Wuse 2', ARRAY['/live-band-abuja.png'], ARRAY['Band Equipment', 'Sound Systems', 'Event Memorabilia', 'Custom Merchandise'], 'Abuja', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Government Event Tent Setup', 'Professional tent decorations for official events', 300000, 'tent_decorations', 'Asokoro', ARRAY['/conference-planning-abuja.png'], ARRAY['Official Events', 'Protocol Setup', 'Government Standards', 'Security Compliant'], 'Abuja', 4.8),

-- Ekiti Services
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Traditional Photography Studio', 'Cultural event photography studio with traditional themes', 65000, 'hotel', 'Ado-Ekiti', ARRAY['/traditional-photography-ekiti.png'], ARRAY['Cultural Events', 'Traditional Themes', 'Local Expertise', 'Digital Albums'], 'Ekiti', 4.5),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Natural Hair Styling Suite', 'Authentic African hair styling and braiding suite', 25000, 'hotel', 'Ikere-Ekiti', ARRAY['/natural-hair-ekiti.png'], ARRAY['Traditional Braiding', 'Natural Hair Care', 'Cultural Styles', 'Organic Products'], 'Ekiti', 4.6),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Cultural Music Equipment', 'Traditional Yoruba music instruments and equipment', 55000, 'souvenirs', 'Ado-Ekiti', ARRAY['/cultural-music-ekiti.png'], ARRAY['Traditional Instruments', 'Cultural Artifacts', 'Music Equipment', 'Educational Materials'], 'Ekiti', 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Festival Tent Decorations', 'Traditional decorations for cultural festivals', 85000, 'tent_decorations', 'Ijero-Ekiti', ARRAY['/festival-planning-ekiti.png'], ARRAY['Cultural Tents', 'Traditional Decorations', 'Festival Setup', 'Cultural Elements'], 'Ekiti', 4.3),

-- Additional Lagos Services
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Fashion Photography Studio', 'High-end fashion photography studio and portrait suite', 95000, 'hotel', 'Banana Island', ARRAY['/fashion-photography-lagos.png'], ARRAY['Fashion Studio', 'Portrait Sessions', 'Professional Setup', 'Retouching Service'], 'Lagos', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Luxury Spa Hotel Suite', 'Premium spa and wellness suite for events', 120000, 'hotel', 'Tarkwa Bay', ARRAY['/spa-services-lagos.png'], ARRAY['Spa Treatments', 'Massage Therapy', 'Beauty Suite', 'Relaxation Services'], 'Lagos', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Celebrity Event Memorabilia', 'Exclusive event souvenirs and celebrity merchandise', 250000, 'souvenirs', 'Surulere', ARRAY['/celebrity-dj-lagos.png'], ARRAY['Celebrity Merchandise', 'Exclusive Souvenirs', 'Event Memorabilia', 'VIP Packages'], 'Lagos', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Luxury Wedding Tent Setup', 'High-end tent decorations for exclusive weddings', 500000, 'tent_decorations', 'Lekki Phase 1', ARRAY['/luxury-planning-lagos.png'], ARRAY['Luxury Tents', 'Exclusive Decorations', 'Premium Setup', 'Designer Elements'], 'Lagos', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Gourmet Wedding Catering', 'High-end catering with international cuisine', 280000, 'catering', 'Victoria Island', ARRAY['/gourmet-catering-lagos.png'], ARRAY['International Cuisine', 'Chef Service', 'Premium Ingredients', 'Fine Dining'], 'Lagos', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Videography Equipment Rental', 'Professional video production equipment and gear', 200000, 'souvenirs', 'Ikoyi', ARRAY['/videography-lagos.png'], ARRAY['4K Equipment', 'Drone Gear', 'Editing Software', 'Professional Cameras'], 'Lagos', 4.7),

-- Additional Abuja Services
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Diplomatic Photography Suite', 'Official photography suite for diplomatic events', 180000, 'hotel', 'Diplomatic Zone', ARRAY['/diplomatic-photography-abuja.png'], ARRAY['Official Events', 'Security Cleared', 'Protocol Photography', 'Government Standards'], 'Abuja', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'VIP Grooming Hotel Suite', 'Premium grooming suite for high-profile clients', 75000, 'hotel', 'Transcorp Hilton', ARRAY['/vip-grooming-abuja.png'], ARRAY['VIP Service', 'Discrete Location', 'Premium Products', 'Private Suite'], 'Abuja', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Orchestra Equipment & Merchandise', 'Classical orchestra equipment and event souvenirs', 350000, 'souvenirs', 'Three Arms Zone', ARRAY['/orchestra-abuja.png'], ARRAY['Orchestra Equipment', 'Classical Instruments', 'Event Programs', 'Musical Merchandise'], 'Abuja', 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Government Event Decorations', 'Specialized tent decorations for official functions', 400000, 'tent_decorations', 'Aso Rock', ARRAY['/government-planning-abuja.png'], ARRAY['Official Decorations', 'Protocol Compliant', 'Security Approved', 'Government Standards'], 'Abuja', 5.0),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Executive Business Catering', 'Premium catering for business and government events', 320000, 'catering', 'Central Business District', ARRAY['/executive-catering-abuja.png'], ARRAY['Business Events', 'Government Approved', 'Security Cleared', 'Premium Service'], 'Abuja', 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Professional Makeup Hotel Suite', 'Elite makeup artists suite for high-profile events', 95000, 'hotel', 'Jahi', ARRAY['/professional-makeup-abuja.png'], ARRAY['Elite Artists', 'High-End Products', 'Celebrity Clients', 'Private Suite'], 'Abuja', 4.8),

-- Additional Ekiti Services  
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Nature Photography Lodge', 'Landscape photography lodge and equipment rental', 40000, 'hotel', 'Ikogosi Warm Springs', ARRAY['/nature-photography-ekiti.png'], ARRAY['Photography Lodge', 'Nature Equipment', 'Outdoor Gear', 'Guide Services'], 'Ekiti', 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Traditional Beauty Hotel Suite', 'Authentic African beauty treatments suite', 18000, 'hotel', 'Ado-Ekiti Farms', ARRAY['/traditional-beauty-ekiti.png'], ARRAY['African Treatments', 'Organic Products', 'Traditional Methods', 'Cultural Suite'], 'Ekiti', 4.3),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Folk Music Instruments & Crafts', 'Traditional folk music instruments and cultural crafts', 30000, 'souvenirs', 'Iyin-Ekiti', ARRAY['/folk-music-ekiti.png'], ARRAY['Folk Instruments', 'Cultural Crafts', 'Traditional Items', 'Educational Materials'], 'Ekiti', 4.5),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Community Event Tent Setup', 'Local tent decorations for community gatherings', 35000, 'tent_decorations', 'Emure-Ekiti', ARRAY['/community-planning-ekiti.png'], ARRAY['Community Tents', 'Local Decorations', 'Cultural Setup', 'Budget Friendly'], 'Ekiti', 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Farm Fresh Catering Services', 'Fresh farm-to-table catering with local ingredients', 28000, 'catering', 'Ekiti State University', ARRAY['/farm-catering-ekiti.png'], ARRAY['Farm Fresh', 'Local Ingredients', 'Organic Food', 'Healthy Options'], 'Ekiti', 4.2),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Cultural Workshop Tent Setup', 'Educational tent setup for cultural workshops', 25000, 'tent_decorations', 'Ekiti Hills', ARRAY['/workshop-planning-ekiti.png'], ARRAY['Educational Tents', 'Workshop Setup', 'Learning Environment', 'Interactive Space'], 'Ekiti', 4.1),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Traditional Henna & Crafts', 'Authentic henna art supplies and traditional crafts', 15000, 'souvenirs', 'Oye-Ekiti', ARRAY['/henna-services-ekiti.png'], ARRAY['Henna Supplies', 'Traditional Patterns', 'Natural Ingredients', 'Cultural Crafts'], 'Ekiti', 4.3);

-- Insert sample experiences
INSERT INTO experiences (host_id, title, description, total_price, car_id, service_ids, location, images, duration_hours, max_participants) VALUES
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Lagos Island Tour + Lunch', 'BMW X3 + Professional driver + Lunch at Eko Hotel', 250000, (SELECT id FROM cars WHERE title = 'BMW X5' LIMIT 1), ARRAY[(SELECT id FROM services WHERE service_type = 'catering' LIMIT 1)], 'Lagos Island', ARRAY['/lagos-island-skyline-tour.png'], 6, 4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Wedding Package Deluxe', 'Luxury car fleet + Decorations + Catering for 100 guests', 1500000, (SELECT id FROM cars WHERE title = 'Mercedes C-Class' LIMIT 1), ARRAY[(SELECT id FROM services WHERE service_type = 'tent_decorations' LIMIT 1), (SELECT id FROM services WHERE service_type = 'catering' LIMIT 1)], 'Lagos', ARRAY['/luxury-wedding-car.png'], 12, 100),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Business Executive Package', 'Mercedes E-Class + Airport pickup + Hotel booking', 450000, (SELECT id FROM cars WHERE title = 'Mercedes C-Class' LIMIT 1), ARRAY[(SELECT id FROM services WHERE service_type = 'hotel' LIMIT 1)], 'Lagos', ARRAY['/executive-mercedes-business-car.png'], 24, 2);

-- Insert sample stays
INSERT INTO stays (host_id, title, description, price_per_night, hotel_type, state, location, images, features, room_count, max_guests, rating) VALUES
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Luxury Oceanview Villa', 'Stunning 4-bedroom villa with private beach access and infinity pool', 150000, 'villa', 'Lagos', 'Lekki Phase 1', ARRAY['/luxury-villa-lekki.png', '/villa-pool-view.png'], ARRAY['Private Beach', 'Infinity Pool', 'Chef Service', 'WiFi', 'Air Conditioning', 'Security'], 4, 8, 4.8),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Executive Hotel Suite', 'Premium hotel suite in the heart of Victoria Island with city views', 85000, 'hotel', 'Lagos', 'Victoria Island', ARRAY['/executive-suite-vi.png', '/hotel-city-view.png'], ARRAY['City View', 'Business Center', 'Gym Access', 'Room Service', 'WiFi', 'Mini Bar'], 1, 2, 4.6),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Modern Apartment Lagos', 'Fully furnished 2-bedroom apartment perfect for business travelers', 45000, 'apartment', 'Lagos', 'Ikeja GRA', ARRAY['/modern-apartment-ikeja.png'], ARRAY['Kitchen', 'Living Room', 'WiFi', 'Air Conditioning', 'Parking', 'Security'], 2, 4, 4.3),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Cozy Guest House', 'Comfortable guest house in a quiet residential area', 25000, 'guest_house', 'Lagos', 'Surulere', ARRAY['/guest-house-surulere.png'], ARRAY['Breakfast', 'WiFi', 'Air Conditioning', 'Parking', 'Garden'], 3, 6, 4.2),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Presidential Villa Abuja', 'Luxury 6-bedroom villa in the prestigious Maitama district', 200000, 'villa', 'Abuja', 'Maitama', ARRAY['/presidential-villa-abuja.png', '/villa-garden-abuja.png'], ARRAY['Private Garden', 'Swimming Pool', 'Gym', 'Study Room', 'WiFi', 'Generator', 'Security'], 6, 12, 4.9),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Business Hotel Abuja', 'Modern hotel in the central business district', 65000, 'hotel', 'Abuja', 'Central Business District', ARRAY['/business-hotel-abuja.png'], ARRAY['Conference Rooms', 'Business Center', 'Restaurant', 'Gym', 'WiFi', 'Laundry'], 1, 2, 4.4),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Family Apartment Abuja', 'Spacious 3-bedroom apartment ideal for families', 55000, 'apartment', 'Abuja', 'Wuse 2', ARRAY['/family-apartment-wuse.png'], ARRAY['Kitchen', 'Living Room', 'Playground Access', 'WiFi', 'Air Conditioning', 'Parking'], 3, 6, 4.1),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Hilltop Villa Ekiti', 'Serene villa with panoramic views of the Ekiti hills', 75000, 'villa', 'Ekiti', 'Ado-Ekiti', ARRAY['/hilltop-villa-ekiti.png'], ARRAY['Mountain View', 'Garden', 'Fireplace', 'WiFi', 'Kitchen', 'Parking'], 3, 6, 4.7),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Traditional Guest House Ekiti', 'Authentic Yoruba-style guest house with cultural experiences', 30000, 'guest_house', 'Ekiti', 'Ikere-Ekiti', ARRAY['/traditional-house-ekiti.png'], ARRAY['Cultural Tours', 'Traditional Meals', 'Garden', 'WiFi', 'Local Guides'], 4, 8, 4.5),
((SELECT id FROM profiles WHERE role = 'host' LIMIT 1), 'Eco-Friendly Apartment', 'Sustainable living apartment with solar power and organic garden', 40000, 'apartment', 'Ekiti', 'Ado-Ekiti', ARRAY['/eco-apartment-ekiti.png'], ARRAY['Solar Power', 'Organic Garden', 'Recycling', 'WiFi', 'Kitchen', 'Bicycle Access'], 2, 4, 4.6);
